    
# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - windows
julia:
  - 1.1
  - nightly

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - clang-3.9
    - graphviz

matrix:
  allow_failures:
    - julia: nightly
    - os: windows
  fast_finish: true

notifications:
  email: false
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y pdf2svg
  - sudo apt-get install -y texlive-latex-base
  - sudo apt-get install -y texlive-binaries
  - sudo apt-get install -y texlive-pictures
  - sudo apt-get install -y texlive-latex-extra
  - sudo pip install dot2tex
  # Every 30 seconds, look for the build log file. If it exists, then
  # start watching its contents and printing them to stdout as they
  # change. This has two effects:
  #   1. it avoids Travis timing out because the build outputs nothing
  #   2. it makes it more obvious what part of the build, if any, gets stuck
  - while sleep 3; do tail ~/build/sisl/Spot.jl/deps/build.log -f ; done &
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --project --color=yes -e 'import Pkg; Pkg.build(); Pkg.test(coverage=true)'
after_success:
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'